server:
  port: 8082

spring:
   application:
     name: notification-service

   rabbitmq:
     host: localhost
     port: 5672
     username: ${username}
     password: ${password}

logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework.integration: DEBUG


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'