spring:
  application:
   name: api-gateway
  security:
    user:
      name: gatewayuser
      password: gatewaypass
  cloud:
    config:
     enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: api-1
          uri: lb://ORDER-SERVICE
          predicates:
           - Path=/order-service/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1

        - id: api-2
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-service/**

        - id: api-3
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/authentication-service/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway-Auth, my-secure-key-123



server:
  port: 8768

jwt:
  secret: ${JWT_SECRET}


eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/






