server:
  port: 8083

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${MongoDBURI}

  rabbitmq:
    host: localhost
    port: 5672
    username: ${username}
    password: ${password}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




