spring:
  application:
    name: rabbitmq-eureka-server
  cloud:
    config:
      enabled: false

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
